import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navbar from '@/components/Utilities/Navbar';
import './globals.css';
import { SessionProvider } from 'next-auth/react';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'CODENIME',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased bg-primary text-text-primary font-inter`}>
        <SessionProvider>
          <Navbar />
          {children}
        </SessionProvider>
      </body>
    </html>
  );
}
